# Generated by Django 5.1.1 on 2024-09-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.TextField(max_length=100)),
                ('scientific_name', models.TextField(max_length=100)),
                ('variety_name', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('age', models.IntegerField()),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('imported', models.BooleanField(default=False)),
            ],
        ),
    ]
