# Generated by Django 5.1.1 on 2024-10-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_alter_plant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='variety_name',
        ),
    ]
